# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6437970e7da3f36cb59a67f45c3a9717668b28d10a223a0c507abec4bbfea12b3a52bf388aab1db6768d56ccfea2a0265919b115b4d4cc250716842c0f3e608

test:
  secret_key_base: afbc9e8f211b75643949ea39e290318fcc2e6a6b7f8c12deb109947258f0e3e3902c78a51294ef547de07c50cf4c845b982eabcf239866dcb075c75d218be2df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
